#!/bin/sh
# Mike OS: Amber - live-build settings. Run "lb config" to apply.
set -e

lb config noauto \
  --distribution bookworm \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --archive-areas "main contrib non-free non-free-firmware" \
  --firmware-chroot false \
  --firmware-binary false \
  --debian-installer none \
  --apt-indices false \
  --bootappend-live "boot=live components quiet splash username=amber user-fullname=Amber hostname=mikeos-amber locales=en_US.UTF-8 keyboard-layouts=us timezone=America/Denver" \
  --iso-volume "MIKEOS_AMBER" \
  --iso-application "Mike OS: Amber" \
  --iso-publisher "Mike OS" \
  "${@}"
